### ISSUE TITLE
Model: reuse at server-side

### ISSUE THREAD

**Issue by dvv** [spine/spine#54]
Hi!

Are there experiments/tutorials in reusing Models at server-side? Say, mongodb/redis-backed Models

TIA,
--Vladimir

**Comment by doublerebel** [comment]
I've been doing this for years so I can have 'isomorphic' models, I didn't realize it wasn't a thing for other people (until I was searching for some answers about Model inheritance just now).

Examples:
https://github.com/nextorigin/spine-couch/blob/master/src/spine-couch.coffee
https://github.com/nextorigin/ten-ply-crest/blob/master/src/models/vault.coffee

Have to be careful how many records I keep in memory, but it works like a charm.  Combine it with this and you get instant Spine-compatible REST API for express:

https://github.com/nextorigin/xanax/blob/master/src/xanax.coffee

I'll write a blog post about this stack at some point soon, since it's powering several of my APIs.
